apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-model-monitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: service-model-monitor
  endpoints:
  - interval: 30s