apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: service-app
  endpoints:
  - interval: 30s
