apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-alerts
  labels:
    release: myprom
spec:
  groups:
  - name: service.rules
    rules:
    - alert: HighRequestRate
      expr: rate(page_requests_total[1m]) > 15
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High request rate"
        description: "The page is receiving more than 15 requests per minute for the last 2 minutes."