apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-alerts
  namespace: monitoring
spec:
  groups:
  - name: service.rules
    rules:
    - alert: HighRequestRate
      expr: rate(http_requests_total[2m]) > 15
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High request rate"
        description: "The service is receiving more than 15 requests per minute for the last 2 minutes."
