apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:  
      labels: { app: app,  version: v1 }
    spec:
      containers:
      - name: app
        image: ghcr.io/remla24-team-5/app:v0.0.8
        ports:
        - containerPort: 5000
        env:
        - name: model_service_url
          valueFrom:
            configMapKeyRef:
              name: config
              key: model.url
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:  
      labels: { app: app,  version: v2 }
    spec:
      containers:
      - name: app
        image: ghcr.io/remla24-team-5/app:v0.0.9
        ports:
        - containerPort: 5000
        env:
        - name: model_service_url
          valueFrom:
            configMapKeyRef:
              name: config
              key: model.url
---
apiVersion: v1
kind: Service
metadata:
  name: service-app
  labels:
    app: service-app-monitor
spec:
  selector:
    app: app
  ports:
  - port: 5000
    targetPort: 5000
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: app-monitor
#   labels:
#     release: app-prometheus
# spec:
#   selector:
#     matchLabels:
#       app: service-app
#   endpoints:
#   - interval: 5s # change once working
