apiVersion: v1
kind: Service
metadata:
  name: my-service-app
spec:
  selector:
    app: myapp
  ports:
    - name: app
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-model-service
spec:
  selector:
    app: myapp
  ports:
    - name: model-service
      protocol: TCP
      port: 8000
      targetPort: 8000