apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dashboard
  labels:
    grafana_dashboard: "1"
data:
  custom-dashboard.json: |
    {
      "id": null,
      "title": "Custom Metrics Dashboard",
      "tags": [],
      "timezone": "browser",
      "schemaVersion": 21,
      "version": 1,
      "refresh": "5s",
      "panels": [
        {
          "id": 1,
          "type": "graph",
          "title": "CPU Usage",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
              "legendFormat": "{{instance}}"
            }
          ],
          "gridPos": {
            "x": 0,
            "y": 0,
            "w": 12,
            "h": 6
          }
        },
        {
          "id": 2,
          "type": "gauge",
          "title": "Memory Usage",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes)",
              "format": "bytes"
            }
          ],
          "gridPos": {
            "x": 0,
            "y": 6,
            "w": 6,
            "h": 6
          }
        },
        {
          "id": 3,
          "type": "graph",
          "title": "Number of Requests",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "sum(rate(http_requests_total[5m]))",
              "legendFormat": "Requests"
            }
          ],
          "gridPos": {
            "x": 6,
            "y": 6,
            "w": 6,
            "h": 6
          }
        }
      ],
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "annotations": {
        "list": []
      },
      "editable": true,
      "hideControls": false,
      "sharedCrosshair": false,
      "links": []
    }