{
 "title": "Custom Metrics Dashboard for Shadow Launch",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Model Request Count",
   "type": "graph",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "rate(requests_to_model_total[5m])",
     "legendFormat": "Model Requests Rate"
    }
   ]
  },
  {
   "title": "Phishing Count",
   "type": "graph",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "rate(model_phishing_detection_total[5m])",
     "legendFormat": "Phishing Detections Rate"
    }
   ]
  },
  {
   "title": "Phishing Rate",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 36, "w": 12, "h": 9 },
   "targets": [
    { "expr": "model_phishing_rate", "legendFormat": "Phishing Rate" }
   ]
  },
  {
   "title": "Average Phishing Rate",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 45, "w": 12, "h": 9 },
   "targets": [
    { "expr": "avg(phishing_rate)", "legendFormat": "Phishing Rate" }
   ]
  }
 ]
}