apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dashboard-shadow-launch
  labels:
    grafana_dashboard: "2"
data:
  custom-dashboard.json: |
    {
      "id": null,
      "title": "Custom Metrics Dashboard for Shadow Launch",
      "tags": [],
      "timezone": "browser",
      "schemaVersion": 21,
      "version": 1,
      "refresh": "5s",
      "panels": [
        {
          "id": 4,
          "type": "graph",
          "title": "Model Request Count",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "rate(requests_to_model_total[5m])",
              "legendFormat": "Model Requests Rate"
            }
          ],
          "gridPos": {
            "x": 12,
            "y": 9,
            "w": 12,
            "h": 9
          }
        },
        {
          "id": 5,
          "type": "graph",
          "title": "Phishing Count",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "rate(model_phishing_detection_total[5m])",
              "legendFormat": "Phishing Detections Rate"
            }
          ],
          "gridPos": {
            "x": 0,
            "y": 18,
            "w": 12,
            "h": 9
          }
        },
        {
          "id": 9,
          "type": "gauge",
          "title": "Phishing Rate",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "model_phishing_rate",
              "legendFormat": "Phishing Rate"
            }
          ],
          "gridPos": {
            "x": 0,
            "y": 36,
            "w": 12,
            "h": 9
          },
          "fieldConfig": {
            "defaults": {
              "min": 0,
              "max": 100
            }
          }
        },
        {
          "id": 12,
          "type": "gauge",
          "title": "Average Phishing Rate",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "avg(phishing_rate)",
              "legendFormat": "Phishing Rate"
            }
          ],
          "gridPos": {
            "x": 12,
            "y": 45,
            "w": 12,
            "h": 9
          },
          "fieldConfig": {
            "defaults": {
              "min": 0,
              "max": 100
            }
          }
        }
      ],
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "annotations": {
        "list": []
      },
      "editable": true,
      "hideControls": false,
      "sharedCrosshair": false,
      "links": []
    }