---
- name: Setup Kubernetes Cluster
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        update_cache: yes
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

- name: Install k3s on control-plane
  hosts: controller
  become: yes
  tasks:        
    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server --node-external-ip={{ ansible_host }} --write-kubeconfig-mode=644
      args:
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Fetch k3s token to local machine
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: ./k3s_token
        flat: yes

    - name: Fetch kubeconfig to local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3s.yaml
        flat: yes

- name: Install k3s on worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: Get k3s token from local machine
      slurp:
        src: /vagrant/playbooks/k3s_token
      register: k3s_token

    - name: Join worker nodes to the cluster
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['controller'].ansible_host }}:6443 K3S_TOKEN={{ k3s_token['content'] | b64decode | regex_replace('\n', '')}} sh -s - agent --node-external-ip={{ ansible_host }}