---
- name: Start Minikube and Setup Cluster
  hosts: controller
  become: yes
  tasks:
    - name: Start Minikube
      command: minikube start --driver=docker --force # did not work without --force

    - name: Enable Ingress addon
      command: minikube addons enable ingress

    - name: Apply Kubernetes yml files
      shell: |
        minikube kubectl -- apply -f vagrant/environment.yml
        minikube kubectl -- apply -f vagrant/Deployment.yml
        minikube kubectl -- apply -f vagrant/Service.yml
        minikube kubectl -- apply -f vagrant/Ingress.yml