---
- name: Setup Kubernetes Cluster
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        update_cache: yes
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

- name: Install k3s on control-plane
  hosts: controller
  become: yes
  tasks:
    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server --node-ip={{ ansible_host }}
      args:
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Fetch k3s token to local machine
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: ./k3s_token
        flat: yes

    - name: Fetch kubeconfig to local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3s.yaml
        flat: yes

    - name: Ensure .kube directory exists
      file:
        path: /home/vagrant/.kube
        state: directory
        mode: '0755'
        owner: vagrant
        group: vagrant

    - name: Copy kubeconfig to control-plane user home
      command: cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config

    - name: Change ownership of kubeconfig
      file:
        path: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: '0644'

- name: Install dashboards on control-plane
  hosts: controller
  become: yes
  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add Helm repositories
      shell: |
        helm repo add prom-repo https://prometheus-community.github.io/helm-charts
        helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
        helm repo update
    
    - name: Copy Grafana dashboard ConfigMap to VM
      copy:
        content: "{{ lookup('file', './grafana-config.yaml') }}"
        dest: /home/vagrant/grafana-config.yaml

    - name: Install Prometheus and Grafana
      shell: |
        export KUBECONFIG=/home/vagrant/.kube/config
        kubectl create namespace monitoring
        kubectl apply -f /home/vagrant/grafana-config.yaml
        helm install myprom prom-repo/kube-prometheus-stack --namespace monitoring 
      args:
        creates: /var/lib/rancher/k3s/server/manifests/prometheus.yaml

    # times out 
    # - name: Install Kubernetes Dashboard
    #   shell: |
    #     helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard 
    #   args:
    #     creates: /var/lib/rancher/k3s/server/manifests/kubernetes-dashboard.yaml

- name: Install k3s on worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: Get k3s token from local machine
      slurp:
        src: /vagrant/playbooks/k3s_token
      register: k3s_token

    - name: Ensure .kube directory exists
      file:
        path: /home/vagrant/.kube
        state: directory
        mode: '0755'
        owner: vagrant
        group: vagrant

    - name: copy ./k3s.yaml from local machine to worker nodes
      copy:
        content: "{{ lookup('file', './k3s.yaml') }}"
        dest: /home/vagrant/.kube/config

    - name: Change ownership of kubeconfig
      file:
        path: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: set correct api server
      replace:
        path: /home/vagrant/.kube/config
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://192.168.56.10:6443'

    - name: Join worker nodes to the cluster
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['controller'].ansible_host }}:6443 K3S_TOKEN={{ k3s_token['content'] | b64decode | regex_replace('\n', '')}} sh -s - agent --node-ip={{ ansible_host }}