---
- name: Start Minikube and Setup Cluster
  hosts: controller
  become: yes
  tasks:
    - name: Start Minikube
      command: minikube start --driver=docker --force # did not work without --force

    - name: Enable Ingress addon
      command: minikube addons enable ingress

    # MORE