---
- name: Start Minikube and Setup Cluster
  hosts: controller
  become: yes
  tasks:
    - name: Start Minikube
      command: minikube start --driver=docker --force # did not work without --force

    - name: Enable Ingress addon
      command: minikube addons enable ingress

    - name: Apply Kubernetes YAML files
      shell: |
        kubectl apply -f kubernetes/Deployment.yaml
        kubectl apply -f kubernetes/Service.yaml
        kubectl apply -f kubernetes/Ingress.yaml