---
- name: Setup Kubernetes Cluster
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        update_cache: yes
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

- name: Install k3s on control-plane
  hosts: controller
  become: yes
  tasks:
    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server --node-external-ip={{ ansible_host }} --write-kubeconfig-mode=644
      args:
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Set correct server address in kubeconfig
      replace:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://192.168.56.10:6443'

    - name: Fetch k3s token to local machine
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: ./k3s_token
        flat: yes

    - name: Fetch kubeconfig to local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3s.yaml
        flat: yes

- name: Install dashboards on control-plane
  hosts: controller
  become: yes
  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add Helm repositories
      shell: |
        helm repo add prom-repo https://prometheus-community.github.io/helm-charts
        helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
        helm repo update

    - name: Install Prometheus and Grafana
      shell: |
        export KUBECONFIG=/vagrant/playbooks/k3s.yaml
        kubectl apply -f /vagrant/playbooks/grafana-config.yaml 
        kubectl apply -f /vagrant/monitoring/monitoring.yml
        helm install myprom prom-repo/kube-prometheus-stack -f /vagrant/kubernetes/grafana-value.yml -f /vagrant/kubernetes/prometheus-value.yml

#        kubectl apply -f /vagrant/monitoring/prometheus_rule.yml
#        kubectl apply -f /vagrant/monitoring/alert_manager.yml


# - name: Install k3s on worker nodes
#   hosts: workers
#   become: yes
#   tasks:
#     - name: Get k3s token from local machine
#       slurp:
#         src: /vagrant/playbooks/k3s_token
#       register: k3s_token

#     - name: Join worker nodes to the cluster
#       shell: |
#         curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['controller'].ansible_host }}:6443 K3S_TOKEN={{ k3s_token['content'] | b64decode | regex_replace('\n', '')}} sh -s - agent --node-external-ip={{ ansible_host }}

- name: Setup cluster
  hosts: controller
  become: yes
  tasks:
    - name: Apply Kubernetes yml files
      shell: |
        kubectl apply -f /vagrant/kubernetes/environment.yml
        kubectl apply -f /vagrant/kubernetes/app.yml
        kubectl apply -f /vagrant/kubernetes/model-service.yml
        kubectl apply -f /vagrant/kubernetes/ingress.yml
