---
- name: Start Minikube and Setup Cluster
  hosts: controller
  become: yes
  tasks:
    - name: Start Minikube
      command: minikube start --driver=docker --force # did not work without --force

    - name: Enable Ingress addon
      command: minikube addons enable ingress

    - name: Apply Kubernetes YAML files
      shell: |
        minikube kubectl -- apply -f vagrant/kubernetes/environment.yaml
        minikube kubectl -- apply -f vagrant/kubernetes/Deployment.yaml
        minikube kubectl -- apply -f vagrant/kubernetes/Service.yaml
        minikube kubectl -- apply -f vagrant/kubernetes/Ingress.yaml